spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    virtual-host: /
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/mp?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  # 配置扫描xml
  mapper-locations=classpath: mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.pojo
# 关闭自动驼峰映射，该参数不能和mybatis-plus.config-location同时存在
  configuration:
    map-underscore-to-camel-case: false
